### PR TITLE
Hello Microverse project pull request

### PR DESCRIPTION
**Pull request by Atifzada**
In this PR, I did the following:

- Added the `index.html` file.
- Added the `style.css` file.
- Added the linters file.
- Added the `test.md` file to the `.gitignore` file.
- Ensured there was no linter error
- Documented the project in a professional way.

### CODE REVIEW

**Review by DuaneDave — CHANGES_REQUESTED** [review]
Hi @Atifzada  👋 , 

Good job so far on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Linter checks are passing
✔️Good PR heading

## Required Changes ♻️
- After the acknowledgement section, a  professional readme usually contains a link that links to a LICENSE file. Kindly add a link to your LICENSE file here to make the readme more professional.

mit


Visit this [link](https://github.com/microverseinc/readme-template#-license-:~:text=to%20top)-,%F0%9F%93%9D,.%20You%20can%20also%20use%20any%20other%20license%20if%20you%20wish.,-(back%20to) to see an example

- Please include a license file in this project in order to make it more personalized and professional. Here is what a [LICENSE](https://github.com/DuaneDave/Bike-rental-api/blob/dev/LICENSE) look like
- A good PR summary must be descriptive such that it clearly outlines all the things done in a given milestone. Kindly edit the PR summary by clicking the icon marked blue in the screenshot. Doing so will make it easier for reviewers to know what you have done.
blue


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- To make your commit messages more professional, always capitalize the first letter.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Atifzada** [comment]
hi @DuaneDave 
Added a license section to the README file to specify the terms and conditions of use for the project. Included the MIT License.

**Comment by Atifzada** [comment]
Hi   *DuaneDave,*

*I have made the changed as per the requirement please review as soon you
find time.*

*Thank you*
Atif Zada
+92-325-9787407

**Review by abdallahmalima — APPROVED** [review]
Hi @Atifzada , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
   - LICENSE file added ✔
   - Descriptive PR ✔
## Optional suggestions
- [OPTIONAL] You have done a great job💪 of including all the required sections in your README file. Please 🙏 remove the `Live demo` section as you have not deployed your app. This will make all the documented sections in the README file more realistic👍.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
